insert into manager (id, name) values (1, 'Drache');
insert into manager (id, name) values (2, 'Miko');
insert into manager (id, name) values (3, 'Cabrara');
insert into manager (id, name) values (4, 'Van Salzberger');
insert into manager (id, name) values (5, 'Lamberts');
insert into manager (id, name) values (6, 'Corfield');
insert into manager (id, name) values (7, 'Armatidge');
insert into manager (id, name) values (8, 'McCourt');
insert into manager (id, name) values (9, 'Hembrow');

insert into employee (id, name, surname, role, MANAGER_ID, salary) values (0, 'Filmore', 'De Domenico', 'Engineering', '1', '18141.77');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (2, 'Lila', 'Chellenham', 'Sales', '6', '1767.37');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (3, 'Cleveland', 'Else', 'Services', '7', '5495.50');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (4, 'Kaspar', 'Curl', 'Support', '4', '2476.12');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (5, 'Vanya', 'Andreutti', 'Business Development', '4', '15560.76');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (6, 'Lynde', 'Adolf', 'Research and Development', '9', '4062.19');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (7, 'Brittani', 'Sherwin', 'Sales', '1', '15631.65');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (8, 'Erik', 'Odger', 'Human Resources', '2', '18368.33');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (9, 'Reina', 'Peet', 'Training', '1', '14485.88');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (10, 'Rik', 'Layburn', 'Business Development', '9', '1819.96');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (11, 'Samuel', 'Flanders', 'Research and Development', '3', '4211.66');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (12, 'Welbie', 'Traher', 'Training', '9', '10436.94');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (13, 'Roobbie', 'Cleaton', 'Accounting', '8', '17287.96');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (14, 'Brianna', 'Merwood', 'Marketing', '3', '6078.99');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (15, 'Eleni', 'Melloy', 'Business Development', '5', '15544.58');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (16, 'Bunny', 'Merkle', 'Services', '5', '7436.95');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (17, 'Lucila', 'Riveles', 'Sales', '6', '15345.07');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (18, 'Margo', 'Jeskins', 'Marketing', '3', '12431.35');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (19, 'Reggi', 'McArdell', 'Accounting', '1', '3967.26');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (20, 'Woodie', 'Hasson', 'Services', '4', '2427.73');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (21, 'Gawain', 'Neilands', 'Human Resources', '4', '6045.57');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (22, 'Fredelia', 'Shepland', 'Support', '1', '5872.75');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (23, 'Melodee', 'Loukes', 'Research and Development', '6', '8933.57');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (24, 'Hubie', 'Zukerman', 'Human Resources', '1', '18877.87');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (25, 'Grazia', 'Allewell', 'Services', '8', '4045.09');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (26, 'Brandise', 'Gleadhell', 'Training', '9', '16196.85');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (27, 'Chick', 'McBoyle', 'Accounting', '3', '6923.25');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (28, 'Mae', 'Petty', 'Product Management', '8', '9710.89');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (29, 'Thadeus', 'Caiger', 'Product Management', '7', '18662.08');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (30, 'Gaby', 'Flott', 'Engineering', '9', '9009.69');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (31, 'Gaby', 'Inglefield', 'Human Resources', '9', '18181.95');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (32, 'Jervis', 'Armall', 'Services', '1', '9661.00');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (33, 'Leighton', 'Hamblyn', 'Human Resources', '2', '4919.41');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (34, 'Philly', 'Olliver', 'Legal', '1', '3665.82');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (35, 'Godart', 'Skey', 'Training', '4', '3214.05');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (36, 'Suzann', 'Dahlback', 'Marketing', '1', '9344.42');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (37, 'Marv', 'Ciccetti', 'Human Resources', '1', '4111.31');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (38, 'Braden', 'Kezourec', 'Accounting', '4', '17155.24');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (39, 'Gilly', 'Kuschel', 'Training', '2', '7759.21');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (40, 'Ikey', 'Lavell', 'Services', '1', '9746.26');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (41, 'Mathe', 'Springthorpe', 'Business Development', '9', '13645.06');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (42, 'Randie', 'Pullin', 'Marketing', '1', '16235.97');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (43, 'Garreth', 'Myring', 'Research and Development', '5', '13776.99');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (44, 'Meredith', 'Strewther', 'Marketing', '4', '7416.18');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (45, 'Fritz', 'Killelea', 'Engineering', '4', '5039.12');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (46, 'Cherye', 'Devericks', 'Marketing', '7', '5718.60');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (47, 'Dinny', 'Aland', 'Support', '3', '8974.80');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (48, 'Dionne', 'Heamus', 'Sales', '6', '4304.65');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (49, 'Damon', 'Esser', 'Sales', '4', '16684.02');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (50, 'Wynne', 'Hatry', 'Training', '5', '3342.88');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (51, 'Konrad', 'Hibbart', 'Research and Development', '2', '14582.76');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (52, 'Tam', 'Aspinall', 'Product Management', '9', '13796.82');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (53, 'Lucie', 'Tallon', 'Training', '1', '12953.34');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (54, 'Filip', 'Deverille', 'Legal', '2', '13640.26');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (55, 'Rog', 'Rayne', 'Business Development', '6', '2232.83');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (56, 'Marjie', 'Curtiss', 'Product Management', '3', '19339.94');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (57, 'Emmott', 'Entreis', 'Business Development', '5', '12590.58');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (58, 'Maura', 'Watt', 'Services', '6', '1069.53');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (59, 'Brenn', 'Lappine', 'Services', '2', '17642.86');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (60, 'Amara', 'Conor', 'Marketing', '6', '13241.77');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (61, 'Martina', 'Rosenblatt', 'Marketing', '7', '4126.55');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (62, 'Steffi', 'Tapner', 'Engineering', '5', '19138.31');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (63, 'Neils', 'Braferton', 'Legal', '9', '11837.25');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (64, 'Daffie', 'Osichev', 'Support', '2', '18313.64');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (65, 'Miller', 'Klauber', 'Accounting', '1', '13906.66');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (66, 'Jena', 'Glentz', 'Services', '1', '9758.14');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (67, 'Ainslee', 'Le Monnier', 'Services', '5', '14140.11');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (68, 'Lilyan', 'Bradick', 'Sales', '7', '8592.92');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (69, 'Halimeda', 'Scruby', 'Support', '6', '14965.44');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (70, 'Nolan', 'Errowe', 'Engineering', '1', '4440.20');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (71, 'Mada', 'Lammerding', 'Sales', '5', '10348.52');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (72, 'Hannah', 'Matic', 'Business Development', '4', '18329.58');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (73, 'Laura', 'Wedge', 'Product Management', '9', '16982.31');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (74, 'Kirk', 'Jentin', 'Support', '1', '7734.31');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (75, 'Trista', 'Normavill', 'Sales', '6', '6912.61');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (76, 'Daren', 'Lander', 'Services', '5', '4983.67');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (77, 'Aubree', 'Wason', 'Training', '1', '13719.32');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (78, 'Giuseppe', 'Danforth', 'Accounting', '8', '10653.38');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (79, 'Aubrie', 'Inglesent', 'Services', '8', '15346.14');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (80, 'Josephina', 'Ducarne', 'Research and Development', '3', '10255.23');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (81, 'Jude', 'Millington', 'Marketing', '5', '6895.42');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (82, 'Pepita', 'Blackler', 'Research and Development', '1', '1813.69');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (83, 'Josepha', 'Bignall', 'Research and Development', '7', '16786.75');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (84, 'Elli', 'Smorthwaite', 'Engineering', '1', '2955.66');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (85, 'Kristan', 'Danielis', 'Research and Development', null, null);
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (86, 'Vikky', 'Simenot', 'Services', '1', '15425.50');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (87, 'Giavani', 'MacMakin', 'Marketing', '2', '1330.97');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (88, 'Uta', 'Alebrooke', 'Product Management', '1', '4860.89');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (89, 'Leoine', 'Thredder', 'Legal', '8', '8936.03');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (90, 'Trula', 'Sawle', 'Legal', '2', '10556.19');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (91, 'Carrol', 'Saunder', 'Support', '1', '18054.85');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (92, 'Petunia', 'Skyner', 'Accounting', '5', '12913.12');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (93, 'Charley', 'Conley', 'Business Development', '5', '13393.86');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (94, 'Rand', 'Buggs', 'Training', '1', '18850.87');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (95, 'Gertrud', 'Hasker', 'Sales', '4', '15383.82');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (96, 'Cosme', 'Maylin', 'Business Development', '7', '7277.26');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (97, 'Lucio', 'Worster', 'Accounting', '1', '8573.79');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (98, 'Georgia', 'Ralph', 'Marketing', '2', '15627.05');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (99, 'Dorey', 'Lyven', 'Business Development', '1', '7698.26');
insert into employee (id, name, surname, role, MANAGER_ID, salary) values (100, 'Grace', 'Alyokhin', 'Marketing', '2', '18582.33');
